---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/
    platform: magento
    server_name: dev.batterystation.co.uk
    database: magento
    database_import_src: /var/www/vagrant/import/database.sql
    sys_packages:
      - mcrypt
      - vim
      - git

    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: redis, package: php5-redis }
      - { name: sqlite, package: php5-sqlite }
      - { name: gd, package: php5-gd }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    php_ppa: php5-5.6
    nodejs:
      version: _5.x
      packages: [bower, gulp]
  roles:
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - composer
    - phpunit
    - mysql
    - mongo
    - rabbitmq
    - redis
    - nodejs
